name: StaffJoinAlert
version: '${project.version}'
main: me.rodrigo.staffjoinalert.bukkkit.BukkitStaffJoinAlert
# api-version: '1.20'
author: "Rodrigo R."
commands:
  staffjoinalert:
    usage: "/staffjoinalert"
    description: "Reload config"